# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Project | Vimel Meng
description: >- # this means to ignore newlines until "baseurl:"
  Projects of Vimel Meng.
baseurl: "/bay" # the subpath of the site
url: "https://vimelmeng.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: vimelmeng@gmail.com
      link: mailto:vimelmeng@gmail.com
    - name: WeChat
      value: vimelvv
      link: "#"
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/vimelmeng
    - name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - name: YouTube
      link: http://linkedin.com/in/YourLinkedInUsername
    - name: Instagram
      link: https://www.instagram.com/vimelmeng/
    - name: GitHub
      link: http://github.com/YourGitHubUsername
    - name: Bilibili
      link: https://space.bilibili.com/182812785


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
